ALTER TABLE "SiteHealthLog" ADD COLUMN "occurrences" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "SiteHealthLog" ADD COLUMN "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE "SiteHealthLog" SET "lastSeenAt" = "createdAt";
