'use client';

import { useState } from 'react';
import { inspectDxf, type DxfEntity } from '@/modules/gcode/dxf';
import { convertSvgToGCode, type SvgOptions } from '@/modules/gcode/svg';

function save(name: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function SvgToGCode() {
    const [source, setSource] = useState(''), [result, setResult] = useState<ReturnType<typeof convertSvgToGCode> | null>(null), [error, setError] = useState('');
    const [options, setOptions] = useState<SvgOptions>({ width: 100, feed: 500, plunge: 120, safeZ: 5, cutZ: -1, spindle: 12000, step: 1 });
    const update = (key: keyof SvgOptions, value: string) => setOptions((current) => ({ ...current, [key]: Number(value) }));
    return <div className="space-y-5"><label className="block rounded-xl border border-border p-4 text-sm">Upload SVG (processed in this browser)<input type="file" accept=".svg,image/svg+xml" className="mt-3 block w-full" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; setResult(null); setError(file.size > 2_000_000 ? 'Maximum file size is 2 MB.' : ''); if (file.size <= 2_000_000) setSource(await file.text()); }} /></label>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{([['width', 'Output width (mm)'], ['feed', 'XY feed (mm/min)'], ['plunge', 'Plunge feed (mm/min)'], ['safeZ', 'Safe Z (mm)'], ['cutZ', 'Cut Z (mm)'], ['spindle', 'Spindle RPM'], ['step', 'Sampling step (mm)']] as const).map(([key, label]) => <label key={key} className="text-xs text-muted-foreground">{label}<input type="number" step="any" value={options[key]} onChange={(e) => update(key, e.target.value)} className="mt-1 w-full rounded-lg border border-border bg-background p-3 text-foreground" /></label>)}</div>
        <button type="button" className="rounded-lg bg-foreground px-4 py-3 text-sm font-bold text-background" onClick={() => { try { setResult(convertSvgToGCode(source, options)); setError(''); } catch (e) { setResult(null); setError(e instanceof Error ? e.message : 'Conversion failed.'); } }}>Generate G-code</button>
        {error && <p role="alert" className="text-sm text-rose-500">{error}</p>}{result && <div className="space-y-3"><p className="text-sm">{result.shapes} shapes - {result.segments} segments. Origin is at SVG top left; SVG Y is inverted for the CNC XY plane.</p><button type="button" onClick={() => save('svg-toolpath.nc', result.code)} className="rounded-lg border border-border px-4 py-2 text-sm">Download .nc</button><textarea readOnly value={result.code} aria-label="Generated G-code" className="h-72 w-full rounded-lg border border-border bg-background p-3 font-mono text-xs" /></div>}
        <p className="text-xs text-amber-500">Vector outlines only. No cutter compensation, kerf, pocketing or machine specific postprocessor. Verify offsets, orientation, clearance and workholding in your controller simulator before machining.</p></div>;
}
export function DxfInspector() {
    const [result, setResult] = useState<ReturnType<typeof inspectDxf> | null>(null), [error, setError] = useState('');
    const bounds = result?.bounds, width = bounds ? Math.max(bounds.maxX - bounds.minX, 1) : 1, height = bounds ? Math.max(bounds.maxY - bounds.minY, 1) : 1;
    return <div className="space-y-5"><label className="block rounded-xl border border-border p-4 text-sm">Upload ASCII DXF (processed in this browser)<input type="file" accept=".dxf" className="mt-3 block w-full" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { setResult(inspectDxf(await file.text())); setError(''); } catch (e) { setResult(null); setError(e instanceof Error ? e.message : 'Cannot inspect DXF.'); } }} /></label>{error && <p role="alert" className="text-rose-500">{error}</p>}{result && <><div className="grid gap-3 sm:grid-cols-3"><Stat label="Entities" value={Object.values(result.counts).reduce((a, b) => a + b, 0)} /><Stat label="Layers" value={result.layers.length} /><Stat label="Bounds" value={bounds ? `${width.toFixed(2)} × ${height.toFixed(2)} drawing units` : 'Unavailable'} /></div><div className="rounded-xl border border-border p-3"><svg role="img" aria-label="DXF XY geometry preview" viewBox={`${(bounds?.minX ?? 0) - width * .05} ${-(bounds?.maxY ?? 0) - height * .05} ${width * 1.1} ${height * 1.1}`} className="h-80 w-full"><g fill="none" stroke="currentColor" className="text-cyan-500" strokeWidth="1" vectorEffect="non-scaling-stroke">{result.entities.map((e: DxfEntity, index: number) => <path key={index} d={e.points.map((p, i) => `${i ? 'L' : 'M'} ${p.x} ${-p.y}`).join(' ')} vectorEffect="non-scaling-stroke" />)}</g></svg></div><div className="text-sm">{Object.entries(result.counts).map(([kind, count]) => <span key={kind} className="mr-3">{kind}: {count}</span>)}<p className="mt-2">Layers: {result.layers.join(', ') || 'None'}</p>{result.unsupported.length > 0 && <p className="mt-2 text-amber-500">Not previewed: {result.unsupported.join(', ')}</p>}</div><p className="text-xs text-muted-foreground">Drawing units are not inferred. Bulged polyline segments and nested blocks need CAD verification.</p></>}</div>;
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-border p-4"><p className="text-xs text-muted-foreground">{label}</p><strong>{value}</strong></div>; }
