'use client';

import { useMemo, useState } from 'react';
import { CopyButton } from './CopyButton';

export type QuickToolMode = 'text' | 'json' | 'encoder' | 'url' | 'uuid' | 'password' | 'color' | 'subtitles' | 'units' | 'calculators';
const area = 'w-full rounded-xl border border-border bg-foreground/[0.02] p-4 font-mono text-sm leading-6 outline-none focus:ring-2 focus:ring-cyan-500';
const button = 'min-h-10 rounded-lg border border-border px-3 text-xs font-bold transition hover:bg-muted';

function titleCase(value: string) { return value.toLowerCase().replace(/\b\p{L}/gu, (letter) => letter.toUpperCase()); }
function slug(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function encodeHtml(value: string) { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;'); }
function decodeHtml(value: string) { const node = document.createElement('textarea'); node.innerHTML = value; return node.value; }
function hslFromRgb(r: number, g: number, b: number) { r /= 255; g /= 255; b /= 255; const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min; let h = 0; const l = (max + min) / 2; if (d) { if (max === r) h = ((g - b) / d) % 6; else if (max === g) h = (b - r) / d + 2; else h = (r - g) / d + 4; h = Math.round(h * 60); if (h < 0) h += 360; } const s = d ? d / (1 - Math.abs(2 * l - 1)) : 0; return `hsl(${h} ${Math.round(s * 100)}% ${Math.round(l * 100)}%)`; }

export function QuickWebTool({ mode }: { mode: QuickToolMode }) {
    const [input, setInput] = useState(mode === 'json' ? '{"project":"NecrotixLab","active":true}' : mode === 'url' ? 'https://necrotixlab.com/tools?source=lab' : 'NecrotixLab makes useful tools.');
    const [output, setOutput] = useState('');
    const [error, setError] = useState('');
    const [length, setLength] = useState(20);
    const [unitCategory, setUnitCategory] = useState('length');
    const [fromUnit, setFromUnit] = useState('m');
    const [toUnit, setToUnit] = useState('ft');
    const [number, setNumber] = useState('1');

    const words = input.trim() ? input.trim().split(/\s+/).length : 0;
    const units: Record<string, Record<string, number>> = { length: { mm: .001, cm: .01, m: 1, km: 1000, in: .0254, ft: .3048, yd: .9144, mi: 1609.344 }, mass: { mg: .000001, g: .001, kg: 1, oz: .0283495, lb: .453592 }, data: { B: 1, KB: 1000, MB: 1e6, GB: 1e9, KiB: 1024, MiB: 1048576, GiB: 1073741824 }, angle: { deg: 1, rad: 180 / Math.PI, grad: .9 } };
    const unitResult = useMemo(() => { const value = Number(number); if (!Number.isFinite(value)) return ''; if (unitCategory === 'temperature') { const c = fromUnit === 'C' ? value : fromUnit === 'F' ? (value - 32) * 5 / 9 : value - 273.15; return String(toUnit === 'C' ? c : toUnit === 'F' ? c * 9 / 5 + 32 : c + 273.15); } const table = units[unitCategory]; return table ? String(value * table[fromUnit]! / table[toUnit]!) : ''; }, [number, unitCategory, fromUnit, toUnit]);

    const run = (action: string) => { setError(''); try {
        if (mode === 'text') { const actions: Record<string, () => string> = { upper: () => input.toUpperCase(), lower: () => input.toLowerCase(), title: () => titleCase(input), slug: () => slug(input), lines: () => input.replace(/\s*\n+\s*/g, ' '), sort: () => input.split(/\r?\n/).sort((a, b) => a.localeCompare(b)).join('\n') }; setOutput(actions[action]?.() ?? input); }
        if (mode === 'json') { const parsed = JSON.parse(input); setOutput(action === 'minify' ? JSON.stringify(parsed) : JSON.stringify(parsed, null, 2)); }
        if (mode === 'encoder') { setOutput(action === 'url-encode' ? encodeURIComponent(input) : action === 'url-decode' ? decodeURIComponent(input) : action === 'html-encode' ? encodeHtml(input) : decodeHtml(input)); }
        if (mode === 'url') { const url = new URL(input); if (action === 'parse') setOutput(JSON.stringify({ protocol: url.protocol, host: url.host, pathname: url.pathname, query: Object.fromEntries(url.searchParams), hash: url.hash }, null, 2)); else { url.searchParams.set('utm_source', 'necrotixlab'); url.searchParams.set('utm_medium', 'web'); url.searchParams.set('utm_campaign', 'campaign'); setOutput(url.toString()); } }
        if (mode === 'uuid') setOutput(Array.from({ length: action === 'ten' ? 10 : 1 }, () => crypto.randomUUID()).join('\n'));
        if (mode === 'password') { const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*+-=?'; const bytes = crypto.getRandomValues(new Uint32Array(length)); setOutput(Array.from(bytes, (value) => chars[value % chars.length]).join('')); }
        if (mode === 'subtitles') setOutput(action === 'to-srt' ? input.replace(/^WEBVTT\s*/i, '').replace(/(\d\d:\d\d:\d\d)\.(\d{3})/g, '$1,$2').trim().split(/\n\n+/).map((block, i) => `${i + 1}\n${block}`).join('\n\n') : `WEBVTT\n\n${input.replace(/^\d+\s*$/gm, '').replace(/(\d\d:\d\d:\d\d),(\d{3})/g, '$1.$2').replace(/\n{3,}/g, '\n\n').trim()}`);
    } catch (cause) { setOutput(''); setError(cause instanceof Error ? cause.message : 'Unable to process the input.'); } };

    if (mode === 'units') { const available = unitCategory === 'temperature' ? ['C', 'F', 'K'] : Object.keys(units[unitCategory] ?? {}); return <div className="grid gap-5 rounded-2xl border border-border p-5 sm:grid-cols-2 sm:p-6"><label className="text-xs font-bold">Category<select value={unitCategory} onChange={(e) => { const category = e.target.value; const list = category === 'temperature' ? ['C', 'F', 'K'] : Object.keys(units[category] ?? {}); setUnitCategory(category); setFromUnit(list[0]!); setToUnit(list[1]!); }} className={`${area} mt-2`}><option value="length">Length</option><option value="mass">Mass</option><option value="data">Digital storage</option><option value="angle">Angle</option><option value="temperature">Temperature</option></select></label><label className="text-xs font-bold">Value<input value={number} onChange={(e) => setNumber(e.target.value)} className={`${area} mt-2`} /></label><label className="text-xs font-bold">From<select value={fromUnit} onChange={(e) => setFromUnit(e.target.value)} className={`${area} mt-2`}>{available.map((unit) => <option key={unit}>{unit}</option>)}</select></label><label className="text-xs font-bold">To<select value={toUnit} onChange={(e) => setToUnit(e.target.value)} className={`${area} mt-2`}>{available.map((unit) => <option key={unit}>{unit}</option>)}</select></label><div className="rounded-xl bg-foreground/[0.04] p-4 sm:col-span-2"><p className="font-mono text-[9px] uppercase tracking-wider text-cyan-500">Result</p><p className="mt-2 break-all text-2xl font-black">{unitResult || '-'}</p></div></div>; }
    if (mode === 'calculators') { const nums = input.split(/[\s,;]+/).map(Number).filter(Number.isFinite); const sum = nums.reduce((a, b) => a + b, 0); const average = nums.length ? sum / nums.length : 0; return <div className="grid gap-5 lg:grid-cols-2"><label className="text-xs font-bold">Numbers separated by spaces or commas<textarea value={input} onChange={(e) => setInput(e.target.value)} rows={10} className={`${area} mt-2`} /></label><div className="grid gap-3">{[['Count', nums.length], ['Sum', sum], ['Average', average], ['20% of total', sum * .2]].map(([label, value]) => <div key={label} className="rounded-xl border border-border p-4"><p className="font-mono text-[9px] uppercase tracking-wider text-cyan-500">{label}</p><p className="mt-2 text-xl font-black">{String(value)}</p></div>)}</div></div>; }
    if (mode === 'color') { const normalized = /^#[0-9a-f]{6}$/i.test(input.trim()) ? input.trim() : '#22d3ee'; const r = parseInt(normalized.slice(1, 3), 16), g = parseInt(normalized.slice(3, 5), 16), b = parseInt(normalized.slice(5, 7), 16); return <div className="grid gap-6 rounded-2xl border border-border p-5 lg:grid-cols-[.6fr_1.4fr]"><div className="aspect-square rounded-xl border border-border" style={{ backgroundColor: normalized }} /><div><label className="text-xs font-bold">HEX color<div className="mt-2 flex gap-2"><input type="color" value={normalized} onChange={(e) => setInput(e.target.value)} className="h-12 w-16 rounded border border-border bg-transparent" /><input value={input} onChange={(e) => setInput(e.target.value)} className={area} /></div></label><div className="mt-5 grid gap-3"><p className="rounded-xl bg-foreground/[0.04] p-4 font-mono text-sm">RGB: {r}, {g}, {b}</p><p className="rounded-xl bg-foreground/[0.04] p-4 font-mono text-sm">{hslFromRgb(r, g, b)}</p></div></div></div>; }

    const actions: Record<Exclude<QuickToolMode, 'units' | 'calculators' | 'color'>, [string, string][]> = { text: [['upper', 'UPPERCASE'], ['lower', 'lowercase'], ['title', 'Title Case'], ['slug', 'Text to slug'], ['lines', 'Remove line breaks'], ['sort', 'Sort lines']], json: [['format', 'Format & validate'], ['minify', 'Minify']], encoder: [['url-encode', 'URL encode'], ['url-decode', 'URL decode'], ['html-encode', 'HTML encode'], ['html-decode', 'HTML decode']], url: [['parse', 'Parse URL'], ['utm', 'Add UTM template']], uuid: [['one', 'Generate UUID'], ['ten', 'Generate 10']], password: [['generate', 'Generate password']], subtitles: [['to-srt', 'VTT to SRT'], ['to-vtt', 'SRT to VTT']] };
    return <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-border p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold">Input</p>{mode === 'text' ? <p className="font-mono text-[9px] text-muted-foreground">{words} words / {input.length} characters</p> : null}</div>{mode === 'password' ? <label className="mt-4 block text-xs font-bold">Length: {length}<input type="range" min="8" max="64" value={length} onChange={(e) => setLength(Number(e.target.value))} className="mt-3 w-full accent-cyan-500" /></label> : mode === 'uuid' ? null : <textarea value={input} onChange={(e) => setInput(e.target.value)} rows={12} spellCheck={false} className={`${area} mt-3`} />}<div className="mt-4 flex flex-wrap gap-2">{actions[mode as keyof typeof actions]?.map(([id, label]) => <button key={id} type="button" onClick={() => run(id)} className={button}>{label}</button>)}</div>{error ? <p className="mt-3 text-xs text-rose-500">{error}</p> : null}</div><div className="rounded-2xl border border-border p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold">Output</p><CopyButton value={output} /></div><pre className="mt-4 min-h-72 whitespace-pre-wrap break-all rounded-xl bg-foreground/[0.03] p-4 font-mono text-sm leading-6">{output}</pre></div></div>;
}
