'use client';
import { useState } from 'react';
type Site = { finalUrl: string; status: number; server: string; poweredBy: string; contentType: string; checkedAt: string; truncated: boolean; note: string; cms: { name: string; confidence: string; evidence: string[] }[]; panels: { path: string; url: string; status: number | null; finding: string }[] };
export function WhoisSiteInspector({ domain }: { domain: string }) {
    const [admin, setAdmin] = useState(false), [authorized, setAuthorized] = useState(false), [busy, setBusy] = useState(false), [result, setResult] = useState<Site | null>(null), [error, setError] = useState('');
    async function inspect() {
        setBusy(true); setError(''); setResult(null);
        try {
            const response = await fetch('/api/tools/whois/site', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ domain, admin, authorized }), signal: AbortSignal.timeout(15000) });
            const data = await response.json();
            if (!response.ok) throw new Error(data.error || 'Inspection failed');
            setResult(data);
        } catch (e) { setError(e instanceof Error ? e.message : 'Inspection failed'); } finally { setBusy(false); }
    }
    return <section className="rounded-2xl border border-border p-5"><h3 className="font-bold">Website technology & login pages</h3><p className="my-3 text-sm text-muted-foreground">Inspect public homepage HTML and response headers for CMS signatures. Optional login checks request up to five standard paths, without submitting credentials.</p><label className="flex gap-2 text-sm"><input type="checkbox" checked={admin} disabled={busy} onChange={e => setAdmin(e.target.checked)} />Check standard admin / login paths</label>{admin && <label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={authorized} disabled={busy} onChange={e => setAuthorized(e.target.checked)} />I own this website or have permission to check these paths.</label>}<button type="button" onClick={inspect} disabled={busy || admin && !authorized} className="mt-4 rounded-xl border border-border px-4 py-3 disabled:opacity-50">{busy ? 'Inspecting...' : 'Inspect website'}</button>{error && <p role="alert" className="mt-3 text-sm text-rose-500">{error}</p>}{result && <div aria-live="polite" className="mt-4 space-y-3 text-sm"><p className="break-all">{result.finalUrl} · HTTP {result.status}</p><p>Server: {result.server}<br />Powered by: {result.poweredBy}<br />Content type: {result.contentType}</p><h4 className="font-semibold">Detected CMS</h4>{result.cms.length ? result.cms.map(cms => <p key={cms.name}><strong>{cms.name}</strong> · {cms.confidence} evidence<br /><span className="text-muted-foreground">{cms.evidence.join(' · ')}</span></p>) : <p>No recognizable CMS signature. This may be a custom site or a CMS with hidden signatures.</p>}{result.panels.map(panel => <div key={panel.path} className="rounded-xl bg-muted/40 p-3"><a href={panel.url} target="_blank" rel="noopener noreferrer" className="break-all underline">{panel.path}</a><p>{panel.finding} · HTTP {panel.status ?? 'No response'}</p></div>)}<p className="text-xs text-muted-foreground">{result.note} {result.truncated && 'HTML was truncated.'} Checked: {result.checkedAt}</p></div>}</section>;
}
