import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { bookingAddonConfig } from '@addons/Booking/server';
import { calOrigin, MEETING_PLATFORMS, CALENDAR_RECIPIENTS } from '@addons/Booking/settings';
import { saveBookingSettings } from './actions';
export default async function BookingSettings({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
    const session = await auth(); if (!session?.user || !['OWNER', 'ADMIN'].includes(session.user.role)) redirect('/admin');
    const config = await bookingAddonConfig(); if (!config.installed) redirect('/admin/addons?tab=available');
    const origin = calOrigin(process.env.CALDIY_ORIGIN); const params = await searchParams;
    const input = 'mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3 text-sm';
    return <div className="mx-auto max-w-5xl space-y-7"><Link href="/admin/addons?tab=installed" className="text-sm underline">Back to Addons</Link><header><h1 className="text-3xl font-black">Booking settings</h1><p className="mt-3 text-sm text-muted-foreground">Cal.diy manages availability, reservations, approval and notifications. This addon publishes your services inside NecrotixLab.</p></header>
        {params.saved && <p role="status" className="text-sm text-emerald-500">Settings saved.</p>}{params.error && <p role="alert" className="text-sm text-rose-500">{params.error}</p>}
        <section className="rounded-xl border border-border p-5"><h2 className="font-bold">Cal.diy connection</h2><Link href="/admin/bookings" className="mt-3 inline-block text-sm underline">View recorded reservations</Link><p className="mt-3 text-xs text-muted-foreground">Set CALDIY_WEBHOOK_SECRET (32+ characters) in the CMS environment and use the same secret on the Cal.diy webhook. Subscriber path: /api/booking/webhook. Subscribe to booking created, requested, confirmed, rejected, cancelled and rescheduled events.</p><p className="mt-3 break-all text-sm">{origin || 'Not configured. Set CALDIY_ORIGIN to the HTTPS origin of your Cal.diy installation, then restart the CMS.'}</p>{origin && <div className="mt-4 flex flex-wrap gap-4 text-sm">{[['Bookings', '/bookings'], ['Services & approval', '/event-types'], ['Availability', '/availability'], ['Calendars', '/settings/my-account/calendars']].map(([label, path]) => <a key={path} href={`${origin}${path}`} target="_blank" rel="noopener noreferrer" className="underline">{label}</a>)}</div>}</section>
        <form action={saveBookingSettings} className="space-y-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm">Page title<input name="title" defaultValue={config.title} maxLength={120} className={input} /></label><label className="text-sm">Introduction<textarea name="description" defaultValue={config.description} maxLength={600} className={input} /></label></div>
            <section className="space-y-4 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Workflows</h2><label className="block text-sm">Email reminder<select name="reminderHours" defaultValue={config.reminderHours} className={input}><option value="0">Disabled</option><option value="1">1 hour before</option><option value="24">24 hours before</option><option value="48">48 hours before</option></select></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="autoProject" defaultChecked={config.autoProject} />Create a private project when a booking is confirmed</label><p className="text-xs leading-6 text-muted-foreground">Reminders need CMS SMTP and a scheduled POST to /api/booking/reminders with Authorization: Bearer BOOKING_CRON_SECRET. Run every five minutes. Enable either Cal.diy reminders or addon reminders to avoid duplicate messages. Changes apply to subsequent webhook events; existing reservations keep their current queue.</p></section>
            <section className="space-y-4 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Booking emails and calendar invitations</h2>
                <label className="flex items-center gap-3 text-sm"><input type="checkbox" name="confirmationEmails" defaultChecked={config.confirmationEmails} />Email booking details to the client and organizer automatically</label>
                <label className="block text-sm">Calendar invitation scope<select name="calendarMode" defaultValue={config.calendarMode} className={input}><option value="ALL">All confirmed bookings</option><option value="SELECTED">Only individually selected bookings</option></select></label>
                <label className="block text-sm">Calendar recipients<select name="calendarRecipients" defaultValue={config.calendarRecipients} className={input}>{CALENDAR_RECIPIENTS.map(value => <option key={value} value={value}>{({ BOTH: 'Client and organizer', CLIENT: 'Client only', HOST: 'Organizer only', NONE: 'No calendar invitations' })[value]}</option>)}</select></label>
                <p className="text-xs leading-6 text-muted-foreground">The addon emails signed webhook booking details using CMS SMTP and attaches calendar invitations only after confirmation. Invitations require acceptance in the recipient’s calendar app; this does not connect accounts or silently insert events. Pending requests receive a pending-status email without a new calendar event. Select bookings in Reservations or in their details. Calendar preferences apply to new deliveries; changing them does not remove existing external events.</p>
                <p className="text-xs leading-6 text-muted-foreground">The first delivery runs after webhook processing. Schedule POST /api/booking/notifications every five minutes with Authorization: Bearer BOOKING_CRON_SECRET for retries. Keep provider scheduling emails enabled if they contain the cancellation/reschedule links; addon emails are supplemental. If Cal.diy already manages calendar invitations, choose No calendar invitations here to avoid duplicates.</p>
            </section>
            <h2 className="text-xl font-bold">Services</h2><p className="text-sm text-muted-foreground">Use the exact username/event-slug from Cal.diy. Duration here is a display label; match the event type duration in Cal.diy. A blank path removes the service.</p>
            <p className="rounded-lg border border-border p-4 text-xs leading-6">Required booking fields: configure each Cal.diy event type with required first/last name, required email and visible required attendeePhoneNumber. The NecrotixLab form checks these before opening the calendar; Cal.diy must enforce them on its direct links as well. Match platform settings to the actual event location. Connect Zoom/Google Meet/Teams in Cal.diy to generate a real meeting URL; a display label alone does not create a meeting. For Viber, provide contact instructions.</p>
            {Array.from({ length: 8 }, (_, index) => { const service = config.services[index]; return <fieldset key={index} className="grid gap-4 rounded-xl border border-border p-5 sm:grid-cols-2"><legend className="px-2 text-sm font-bold">Service {index + 1}</legend><label className="text-sm">Name<input name={`title-${index}`} defaultValue={service?.title || ''} maxLength={120} className={input} /></label><label className="text-sm">Cal.diy path<input name={`path-${index}`} defaultValue={service?.path || ''} placeholder="username/consultation" maxLength={161} className={input} /></label><label className="text-sm">Description<input name={`description-${index}`} defaultValue={service?.description || ''} maxLength={400} className={input} /></label><label className="text-sm">Category<input name={`category-${index}`} defaultValue={service?.category || ''} maxLength={120} className={input} /></label><label className="text-sm">Meeting platform<select name={`platform-${index}`} defaultValue={service?.platform || 'CALDIY'} className={input}>{MEETING_PLATFORMS.map(value => <option key={value} value={value}>{value.replace(/_/g, ' ')}</option>)}</select></label><label className="text-sm">Cal.diy event type ID<input type="number" name={`eventTypeId-${index}`} min={1} defaultValue={service?.eventTypeId || ''} className={input} /><span className="mt-1 block text-xs text-muted-foreground">Used to match webhook services reliably. If omitted, the public title must match the Cal.diy event title.</span></label><label className="text-sm">Joining instructions<textarea name={`instructions-${index}`} maxLength={1000} defaultValue={service?.instructions || ''} className={input} /></label><label className="text-sm">Duration (minutes)<input type="number" name={`duration-${index}`} defaultValue={service?.duration || 30} min={5} max={480} className={input} /></label></fieldset>; })}
            <button className="min-h-11 rounded-lg bg-foreground px-6 text-sm font-bold text-background">Save settings</button>
        </form>
        <section className="rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Calendar synchronization</h2><div className="mt-5 grid gap-5 sm:grid-cols-3">{[['Google Calendar', 'google-calendar', 'Connect your account in Cal.diy. Select calendars for conflict checking and the destination for new bookings.'], ['Microsoft / Outlook', 'office365-calendar', 'Connect an Outlook or Microsoft 365 account in Cal.diy. Your server must have Microsoft OAuth configured.']].map(([label, slug, text]) => <div key={slug}><h3 className="font-bold">{label}</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">{text}</p>{origin && <a href={`${origin}/apps/${slug}`} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-sm underline">Open connection setup</a>}</div>)}<div><h3 className="font-bold">Samsung Calendar</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">Uses the connected Google calendar, not a separate Samsung API. On your phone: Settings → Accounts and backup → Manage accounts → Google → Sync account → Calendar. Save events to that Google account.</p></div></div><p className="mt-5 text-xs text-muted-foreground">Connection status is managed in Cal.diy. These links do not mean an account is already connected. Addon reminder delivery is shown in Reservations.</p></section>
    </div>;
}
