import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { bookingAddonConfig } from '@addons/Booking/server';
import { MEETING_PLATFORMS, CALENDAR_RECIPIENTS } from '@addons/Booking/settings';
import { saveBookingSettings } from './actions';
export default async function BookingSettings({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
    const session = await auth(); if (!session?.user || !['OWNER', 'ADMIN'].includes(session.user.role)) redirect('/admin');
    const config = await bookingAddonConfig(); if (!config.installed) redirect('/admin/addons?tab=available');
    const params = await searchParams;
    const input = 'mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3 text-sm';
    return <div className="mx-auto max-w-5xl space-y-7"><Link href="/admin/addons?tab=installed" className="text-sm underline">Back to Addons</Link><header><h1 className="text-3xl font-black">Booking settings</h1><p className="mt-3 text-sm text-muted-foreground">NecrotixLab manages availability, requests, approval and email notifications. No external booking server is required.</p></header>
        {params.saved && <p role="status" className="text-sm text-emerald-500">Settings saved.</p>}{params.error && <p role="alert" className="text-sm text-rose-500">{params.error}</p>}
        <form action={saveBookingSettings} className="space-y-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm">Page title<input name="title" defaultValue={config.title} maxLength={120} className={input} /></label><label className="text-sm">Introduction<textarea name="description" defaultValue={config.description} maxLength={600} className={input} /></label></div>
            <section className="space-y-4 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Availability / Работно време</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Timezone<input required name="timeZone" defaultValue={config.timeZone} className={input} /></label><label className="text-sm">Organizer email<input type="email" name="organizerEmail" defaultValue={config.organizerEmail} maxLength={254} className={input} /></label><label className="text-sm">Day starts<input required type="time" name="dayStart" defaultValue={config.dayStart} step={900} className={input} /></label><label className="text-sm">Day ends<input required type="time" name="dayEnd" defaultValue={config.dayEnd} step={900} className={input} /></label><label className="text-sm">Minimum notice (hours)<input type="number" name="leadHours" min={0} max={168} defaultValue={config.leadHours} className={input} /></label><label className="text-sm">Book ahead (days)<input type="number" name="horizonDays" min={1} max={180} defaultValue={config.horizonDays} className={input} /></label><label className="text-sm">Buffer between meetings (minutes)<input type="number" name="bufferMinutes" min={0} max={120} defaultValue={config.bufferMinutes} className={input} /></label></div><fieldset><legend className="text-sm">Working days</legend><div className="mt-3 flex flex-wrap gap-4">{['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].map((day, index) => <label key={day} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="weekdays" value={index} defaultChecked={config.weekdays.includes(index)} />{day}</label>)}</div></fieldset><label className="block text-sm">Unavailable dates (YYYY-MM-DD, one per line)<textarea name="blockedDates" defaultValue={config.blockedDates.join('\n')} rows={4} className={input} /></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="approvalRequired" defaultChecked={config.approvalRequired} />Require approval before confirming a booking</label><p className="text-xs text-muted-foreground">Pending requests occupy their time. All services share one organizer and one schedule. External calendars are not checked for conflicts.</p></section>
            <section className="space-y-4 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Workflows</h2><label className="block text-sm">Email reminder<select name="reminderHours" defaultValue={config.reminderHours} className={input}><option value="0">Disabled</option><option value="1">1 hour before</option><option value="24">24 hours before</option><option value="48">48 hours before</option></select></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="autoProject" defaultChecked={config.autoProject} />Create a private project when a booking is confirmed</label><p className="text-xs leading-6 text-muted-foreground">Reminders need CMS SMTP and a scheduled POST to /api/booking/reminders with Authorization: Bearer BOOKING_CRON_SECRET. Run every five minutes. Changes apply to subsequent bookings and status changes; existing appointments keep their current queue.</p></section>
            <section className="space-y-4 rounded-xl border border-border p-5"><h2 className="text-xl font-bold">Booking emails and calendar invitations</h2>
                <label className="flex items-center gap-3 text-sm"><input type="checkbox" name="confirmationEmails" defaultChecked={config.confirmationEmails} />Email booking details to the client and organizer automatically</label>
                <label className="block text-sm">Calendar invitation scope<select name="calendarMode" defaultValue={config.calendarMode} className={input}><option value="ALL">All confirmed bookings</option><option value="SELECTED">Only individually selected bookings</option></select></label>
                <label className="block text-sm">Calendar recipients<select name="calendarRecipients" defaultValue={config.calendarRecipients} className={input}>{CALENDAR_RECIPIENTS.map(value => <option key={value} value={value}>{({ BOTH: 'Client and organizer', CLIENT: 'Client only', HOST: 'Organizer only', NONE: 'No calendar invitations' })[value]}</option>)}</select></label>
                <p className="text-xs leading-6 text-muted-foreground">The addon emails booking details using CMS SMTP and attaches calendar invitations only after confirmation. Invitations require acceptance in the recipient’s calendar app; this does not connect accounts or silently insert events. Pending requests receive a pending-status email without a new calendar event. Select bookings in Appointments or in their details. Calendar preferences apply to new deliveries; changing them does not remove existing external events.</p>
                <p className="text-xs leading-6 text-muted-foreground">The first delivery runs after booking creation or admin updates. Schedule POST /api/booking/notifications every five minutes with Authorization: Bearer BOOKING_CRON_SECRET for retries. Clients contact you to request cancellation or rescheduling. Manage the change from Appointments.</p>
            </section>
            <section className="rounded-xl border border-border p-5"><h2 className="text-xl font-bold">30-day booking history retention</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Completed/past requests are removed 30 days after the meeting ends; cancelled, rejected and superseded records are removed 30 days after their last status event. Upcoming active appointments are kept. Client details, booking notes, notifications and reminders are deleted; private projects are detached and kept as project work.</p><p className="mt-3 text-xs leading-6 text-muted-foreground">The notifications scheduler performs cleanup even when Booking is inactive or SMTP is unavailable. Alternatively schedule authenticated POST /api/booking/retention daily with BOOKING_CRON_SECRET. This policy applies to CMS records; Backups and downloaded exports need their own retention settings.</p></section>
            <h2 className="text-xl font-bold">Services</h2><p className="text-sm text-muted-foreground">A blank name removes a service. Duration determines the reserved time. Enter a real meeting URL or joining instructions - platform labels do not create Zoom/Meet calls.</p>
            {Array.from({ length: 8 }, (_, index) => { const service = config.services[index]; return <fieldset key={index} className="grid gap-4 rounded-xl border border-border p-5 sm:grid-cols-2"><legend className="px-2 text-sm font-bold">Service {index + 1}</legend><input type="hidden" name={`id-${index}`} value={service?.id || `service-${index}`} /><label className="text-sm">Name<input name={`title-${index}`} defaultValue={service?.title || ''} maxLength={120} className={input} /></label><label className="text-sm">Description<input name={`description-${index}`} defaultValue={service?.description || ''} maxLength={400} className={input} /></label><label className="text-sm">Category<input name={`category-${index}`} defaultValue={service?.category || ''} maxLength={120} className={input} /></label><label className="text-sm">Meeting platform<select name={`platform-${index}`} defaultValue={service?.platform === 'CALDIY' ? 'OTHER' : service?.platform || 'OTHER'} className={input}>{MEETING_PLATFORMS.filter(value => value !== 'CALDIY').map(value => <option key={value} value={value}>{value.replace(/_/g, ' ')}</option>)}</select></label><label className="text-sm">Meeting URL<input type="url" name={`meetingUrl-${index}`} defaultValue={service?.meetingUrl || ''} maxLength={2000} placeholder="https://..." className={input} /></label><label className="text-sm">Joining instructions<textarea name={`instructions-${index}`} maxLength={1000} defaultValue={service?.instructions || ''} className={input} /></label><label className="text-sm">Duration (minutes)<input type="number" name={`duration-${index}`} defaultValue={service?.duration || 30} min={5} max={480} className={input} /></label></fieldset>; })}
            <button className="min-h-11 rounded-lg bg-foreground px-6 text-sm font-bold text-background">Save settings</button>
        </form>
        <p className="text-sm text-muted-foreground">Calendar invitations can be added to Google, Outlook, Apple or Samsung Calendar. Account synchronization and automatic meeting creation are not connected. <Link href="/admin/bookings" className="underline">Manage appointments</Link> · <Link href="/booking" className="underline">Open booking page</Link></p>
    </div>;
}
