import { BookingStatusBadge } from '@/components/admin/BookingStatusBadge';
import { bookingStatusLabel } from '@addons/Booking/status.mjs';
import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { auth } from '@/auth';
import { prisma } from '@/lib/prisma';
import { BOOKING_PROJECT_STATUSES } from '@addons/Booking/workflow-policy';
import { createBookingProject, saveBookingNotes, saveBookingProject, saveBookingCalendarSelection, updateNativeBooking } from '../actions';
import { CalendarActions } from '@addons/Booking/CalendarActions';
import { canAddBookingToCalendar } from '@addons/Booking/calendar';
import { bookingCalendarGuestPath } from '@addons/Booking/calendar-access';
export const dynamic = 'force-dynamic';
export default async function BookingDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; saved?: string }> }) {
    const session = await auth(); if (!session?.user || !['OWNER', 'ADMIN'].includes(session.user.role)) redirect('/admin');
    const { id } = await params; const query = await searchParams;
    const booking = await prisma.bookingReservation.findUnique({ where: { id }, include: { project: true, notifications: { orderBy: { createdAt: 'desc' }, take: 20 }, reminders: { orderBy: { createdAt: 'desc' }, take: 20 } } });
    if (!booking) notFound();
    const calendarPath = canAddBookingToCalendar(booking) ? bookingCalendarGuestPath(booking, process.env.AUTH_SECRET) : null;
    const history = booking.email ? await prisma.bookingReservation.findMany({ where: { email: { equals: booking.email, mode: 'insensitive' } }, orderBy: { startTime: 'desc' }, take: 30 }) : [];
    const input = 'mt-2 min-h-11 w-full rounded-lg border border-border bg-background p-3 text-sm';
    const button = 'min-h-11 rounded-lg bg-foreground px-4 text-sm font-semibold text-background';
    const time = (date: Date) => new Intl.DateTimeFormat('bg-BG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Europe/Sofia' }).format(date);
    return <div className="mx-auto max-w-5xl space-y-6"><Link href="/admin/bookings" className="text-sm underline">Back to appointments</Link><header><BookingStatusBadge booking={booking} /><h1 className="mt-2 text-3xl font-bold tracking-tight">{booking.title}</h1><p className="mt-3 text-sm text-muted-foreground">{time(booking.startTime)} - {time(booking.endTime)} · Europe/Sofia</p></header>
        {query.error && <p role="alert" className="text-sm text-rose-500">{query.error}</p>}{query.saved && <p role="status" className="text-sm text-emerald-500">Booking updated; emails queued.</p>}
        {booking.source === 'NATIVE' && <section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Управление / Manage booking</h2><form action={updateNativeBooking.bind(null, id)} className="mt-4 space-y-4"><label className="block text-sm">New date and time (Booking settings timezone)<input type="datetime-local" name="startTime" step={900} className={input} /></label><label className="block text-sm">Meeting URL<input type="url" name="meetingUrl" maxLength={2000} defaultValue={booking.meetingUrl} className={input} /></label><label className="block text-sm">Joining instructions<textarea name="meetingInstructions" maxLength={1000} defaultValue={booking.meetingInstructions} className={input} /></label><div className="flex flex-wrap gap-3">{['PENDING', 'CONFIRMED'].includes(booking.status) && <><button name="operation" value="approve" className={button}>Одобри / Approve</button><button name="operation" value="reschedule" className={button}>Пренасочи / Reschedule</button><button name="operation" value="decline" className={button}>Откажи / Decline</button></>}<button name="operation" value="details" className={button}>Save joining details</button></div><p className="text-xs text-muted-foreground">Rescheduling approves the new time and sends updated details. Choose within availability; requests are checked for conflicts.</p></form></section>}
        {canAddBookingToCalendar(booking) && <CalendarActions event={booking} downloadHref={`/api/booking/calendar/${encodeURIComponent(id)}`} />}{calendarPath && <p className="text-sm"><Link href={calendarPath} className="underline">Open private customer calendar link</Link><span className="ml-2 text-xs text-muted-foreground">Anyone with this link can view the appointment title/time. Share only with the attendee.</span></p>}
        {booking.rescheduledAt && <p className="rounded-xl border border-sky-500/30 p-4 text-sm">Пренасочен на / Rescheduled on: {time(booking.rescheduledAt)}. {booking.status === 'PENDING' ? 'Новият час очаква одобрение. / The new time awaits approval.' : 'Показаните дата и час са за тази резервация. / The date and time shown belong to this reservation.'}</p>}
        {booking.status === 'RESCHEDULED' && <p className="rounded-xl border border-border p-4 text-sm">Предишен час, заменен с нова резервация. / Previous appointment superseded by a new reservation.</p>}
        <section className="space-y-3 rounded-xl border border-border p-5"><h2 className="font-semibold">Calendar delivery</h2><form action={saveBookingCalendarSelection.bind(null, id)} className="flex flex-wrap items-center gap-3"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="calendarSelected" defaultChecked={booking.calendarSelected} />Include this booking when using individually selected mode</label><button name="operation" value="save" className={button}>Save selection</button>{booking.status === 'CONFIRMED' && <button name="operation" value="send" className={button}>Send calendar invitation</button>}</form>{!booking.organizerEmail && <p role="status" className="text-xs text-amber-500">No organizer email was received from Cal.diy. Organizer notifications cannot be delivered for this record.</p>}<p className="text-xs text-muted-foreground">The global calendar scope and recipient settings still apply. Existing external events are not deleted when this selection is cleared.</p></section>
        <section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Meeting details</h2><p className="mt-3 text-sm">Platform: {booking.platform.replace(/_/g, ' ')}</p>{booking.category && <p className="mt-2 text-sm">Category: {booking.category}</p>}{booking.meetingUrl ? <a href={booking.meetingUrl} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block break-all text-sm underline">Open meeting</a> : <p className="mt-2 text-xs text-muted-foreground">No meeting link received yet.</p>}{booking.meetingInstructions && <p className="mt-3 whitespace-pre-wrap text-sm">{booking.meetingInstructions}</p>}</section>
        <section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Booking email and calendar delivery</h2>{booking.notifications.length ? <ul className="mt-3 divide-y divide-border">{booking.notifications.map(job => <li key={job.id} className="py-3 text-sm"><p>{job.recipientRole} - {job.kind} - {job.status} - {job.attempts} attempts</p><p className="mt-1 text-xs text-muted-foreground">{job.recipientEmail}{job.calendarAttached ? ' - calendar invitation' : ''}{job.sentAt ? ` - sent ${time(job.sentAt)}` : ''}</p>{job.lastError && <p className="mt-1 text-xs text-amber-500">{job.lastError}</p>}</li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">No addon emails queued for this reservation version.</p>}</section>
        <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-6"><section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Private notes</h2><p className="mt-2 text-xs text-muted-foreground">Only visible to administrators. Separate from the attendee’s booking notes.</p><form action={saveBookingNotes.bind(null, id)} className="mt-4 space-y-4"><textarea name="internalNotes" aria-label="Private notes" maxLength={5000} rows={5} defaultValue={booking.internalNotes} className={input} /><button className={button}>Save notes</button></form></section>
            <section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Project</h2>{booking.project ? <form action={saveBookingProject.bind(null, id)} className="mt-4 space-y-4"><label className="block text-sm">Title<input required name="title" maxLength={120} defaultValue={booking.project.title} className={input} /></label><label className="block text-sm">Status<select name="status" defaultValue={booking.project.status} className={input}>{BOOKING_PROJECT_STATUSES.map(status => <option key={status}>{status}</option>)}</select></label><label className="block text-sm">Project notes<textarea name="notes" maxLength={5000} rows={4} defaultValue={booking.project.notes} className={input} /></label><button className={button}>Save project</button></form> : <><p className="my-4 text-sm text-muted-foreground">Create an internal project from a confirmed or completed reservation. Projects stay private in Booking.</p>{['CONFIRMED', 'COMPLETED'].includes(booking.status) && <form action={createBookingProject.bind(null, id)}><button className={button}>Create project</button></form>}</>}</section>
            <section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Reminder delivery</h2>{booking.reminders.length ? <ul className="mt-3 divide-y divide-border">{booking.reminders.map(job => <li key={job.id} className="py-3 text-sm"><p>{job.hours} hours before · {job.status} · {job.attempts} attempts</p><p className="mt-1 text-xs text-muted-foreground">{time(job.dueAt)}{job.sentAt && ` · sent ${time(job.sentAt)}`}</p>{job.lastError && <p className="mt-2 text-xs text-amber-500">{job.lastError}</p>}</li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">No scheduled addon reminder.</p>}</section>
        </div><aside className="space-y-6"><section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Customer</h2><p className="mt-3 text-sm">{booking.customerName || 'Unnamed attendee'}</p><p className="mt-2 break-all text-sm text-muted-foreground">{booking.email}</p>{booking.phone && <p className="mt-2 text-sm">Phone: {booking.phone}</p>}<p className="mt-2 text-xs text-muted-foreground">{booking.timeZone || 'Timezone not provided'}</p>{booking.notes && <p className="mt-4 whitespace-pre-wrap break-words text-sm">{booking.notes}</p>}{booking.reason && <p className="mt-4 whitespace-pre-wrap break-words text-sm">{booking.reason}</p>}</section><section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Customer history</h2><p className="mt-2 text-xs text-muted-foreground">Matched by email. Latest 30 appointments.</p><ul className="mt-3 divide-y divide-border">{history.map(item => <li key={item.id} className="py-3"><Link href={`/admin/bookings/${item.id}`} className="text-sm underline">{item.title}</Link><p className="mt-1 text-xs text-muted-foreground">{time(item.startTime)} · {bookingStatusLabel(item)}</p></li>)}</ul></section></aside></div>
    </div>;
}
