import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { auth } from '@/auth';
import { prisma } from '@/lib/prisma';
import { BOOKING_PROJECT_STATUSES } from '@addons/Booking/workflow-policy';
import { createBookingProject, saveBookingNotes, saveBookingProject } from '../actions';
export const dynamic = 'force-dynamic';
export default async function BookingDetail({ params }: { params: Promise<{ id: string }> }) {
    const session = await auth(); if (!session?.user || !['OWNER', 'ADMIN'].includes(session.user.role)) redirect('/admin');
    const { id } = await params;
    const booking = await prisma.bookingReservation.findUnique({ where: { id }, include: { project: true, reminders: { orderBy: { createdAt: 'desc' }, take: 20 } } });
    if (!booking) notFound();
    const history = booking.email ? await prisma.bookingReservation.findMany({ where: { email: { equals: booking.email, mode: 'insensitive' } }, orderBy: { startTime: 'desc' }, take: 30 }) : [];
    const input = 'mt-2 min-h-11 w-full rounded-lg border border-border bg-background p-3 text-sm';
    const button = 'min-h-11 rounded-lg bg-foreground px-4 text-sm font-semibold text-background';
    const time = (date: Date) => new Intl.DateTimeFormat('bg-BG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Europe/Sofia' }).format(date);
    return <div className="mx-auto max-w-5xl space-y-6"><Link href="/admin/bookings" className="text-sm underline">Back to reservations</Link><header><p className="text-xs text-muted-foreground">{booking.status}</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{booking.title}</h1><p className="mt-3 text-sm text-muted-foreground">{time(booking.startTime)} - {time(booking.endTime)} · Europe/Sofia</p></header>
        <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-6"><section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Private notes</h2><p className="mt-2 text-xs text-muted-foreground">Only visible to administrators. Separate from the attendee’s booking notes.</p><form action={saveBookingNotes.bind(null, id)} className="mt-4 space-y-4"><textarea name="internalNotes" aria-label="Private notes" maxLength={5000} rows={5} defaultValue={booking.internalNotes} className={input} /><button className={button}>Save notes</button></form></section>
            <section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Project</h2>{booking.project ? <form action={saveBookingProject.bind(null, id)} className="mt-4 space-y-4"><label className="block text-sm">Title<input required name="title" maxLength={120} defaultValue={booking.project.title} className={input} /></label><label className="block text-sm">Status<select name="status" defaultValue={booking.project.status} className={input}>{BOOKING_PROJECT_STATUSES.map(status => <option key={status}>{status}</option>)}</select></label><label className="block text-sm">Project notes<textarea name="notes" maxLength={5000} rows={4} defaultValue={booking.project.notes} className={input} /></label><button className={button}>Save project</button></form> : <><p className="my-4 text-sm text-muted-foreground">Create an internal project from a confirmed or completed reservation. Projects stay private in Booking.</p>{['CONFIRMED', 'COMPLETED'].includes(booking.status) && <form action={createBookingProject.bind(null, id)}><button className={button}>Create project</button></form>}</>}</section>
            <section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Reminder delivery</h2>{booking.reminders.length ? <ul className="mt-3 divide-y divide-border">{booking.reminders.map(job => <li key={job.id} className="py-3 text-sm"><p>{job.hours} hours before · {job.status} · {job.attempts} attempts</p><p className="mt-1 text-xs text-muted-foreground">{time(job.dueAt)}{job.sentAt && ` · sent ${time(job.sentAt)}`}</p>{job.lastError && <p className="mt-2 text-xs text-amber-500">{job.lastError}</p>}</li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">No scheduled addon reminder.</p>}</section>
        </div><aside className="space-y-6"><section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Customer</h2><p className="mt-3 text-sm">{booking.customerName || 'Unnamed attendee'}</p><p className="mt-2 break-all text-sm text-muted-foreground">{booking.email}</p><p className="mt-2 text-xs text-muted-foreground">{booking.timeZone || 'Timezone not provided'}</p>{booking.notes && <p className="mt-4 whitespace-pre-wrap break-words text-sm">{booking.notes}</p>}{booking.reason && <p className="mt-4 whitespace-pre-wrap break-words text-sm">{booking.reason}</p>}</section><section className="rounded-xl border border-border p-5"><h2 className="font-semibold">Customer history</h2><p className="mt-2 text-xs text-muted-foreground">Matched by email. Latest 30 reservations.</p><ul className="mt-3 divide-y divide-border">{history.map(item => <li key={item.id} className="py-3"><Link href={`/admin/bookings/${item.id}`} className="text-sm underline">{item.title}</Link><p className="mt-1 text-xs text-muted-foreground">{time(item.startTime)} · {item.status}</p></li>)}</ul></section></aside></div>
    </div>;
}
