import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { prisma } from '@/lib/prisma';
export const dynamic = 'force-dynamic';
export default async function BookingCustomers({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
    const session = await auth(); if (!session?.user || !['OWNER', 'ADMIN'].includes(session.user.role)) redirect('/admin');
    const params = await searchParams; const q = (params.q || '').trim().slice(0, 120);
    const page = Math.min(10000, Math.max(1, Number.parseInt(params.page || '1', 10) || 1));
    const customers = await prisma.bookingReservation.groupBy({ by: ['email'], where: { email: { not: '', ...(q ? { contains: q, mode: 'insensitive' as const } : {}) } }, _count: { _all: true }, _max: { startTime: true }, orderBy: { email: 'asc' }, take: 31, skip: (page - 1) * 30 });
    const rows = await Promise.all(customers.slice(0, 30).map(async customer => ({ ...customer, latest: await prisma.bookingReservation.findFirst({ where: { email: customer.email }, orderBy: { startTime: 'desc' }, select: { id: true, customerName: true } }) })));
    return <div className="mx-auto max-w-5xl space-y-6"><Link href="/admin/bookings" className="text-sm underline">Back to appointments</Link><header><h1 className="text-3xl font-bold tracking-tight">Customers</h1><p className="mt-3 text-sm text-muted-foreground">Customer history from synchronized appointments, grouped by email.</p></header><form className="flex flex-wrap gap-3"><input aria-label="Search customer email" name="q" defaultValue={q} maxLength={120} placeholder="Search by email" className="min-h-11 flex-1 rounded-lg border border-border bg-background px-3 text-sm" /><button className="min-h-11 rounded-lg border border-border px-4 text-sm">Search</button></form><div className="divide-y divide-border overflow-hidden rounded-xl border border-border">{rows.map(item => <article key={item.email} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="font-semibold">{item.latest?.customerName || 'Unnamed attendee'}</h2><p className="mt-1 break-all text-sm text-muted-foreground">{item.email}</p></div><div className="flex items-center gap-4 text-sm"><span>{item._count._all} appointments</span>{item.latest && <Link href={`/admin/bookings/${item.latest.id}`} className="underline">View history</Link>}</div></article>)}{rows.length === 0 && <p className="p-8 text-sm text-muted-foreground">No matching customers.</p>}</div><nav aria-label="Customer pages" className="flex justify-between text-sm">{page > 1 && <Link href={`?page=${page - 1}&q=${encodeURIComponent(q)}`} className="underline">Previous</Link>}{customers.length > 30 && <Link href={`?page=${page + 1}&q=${encodeURIComponent(q)}`} className="ml-auto underline">Next</Link>}</nav></div>;
}
