'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, Clock, Globe2, Mail, Video } from 'lucide-react';
import { normalizeBookingContact, type BookingContact } from './intake';
import { localParts } from './availability';
import { BookingDatePicker } from './BookingDatePicker';
import type { BookingConfig } from './settings';
type Confirmation = { status: string; startTime: string; endTime: string; title: string; timeZone: string };
export function BookingScreen({ config }: { config: BookingConfig }) {
    const [language, setLanguage] = useState<'bg' | 'en'>('bg'); const bg = language === 'bg'; const languageRef = useRef(language);
    useEffect(() => { languageRef.current = language; }, [language]);
    const [step, setStep] = useState(0); const [selected, setSelected] = useState(''); const [date, setDate] = useState(''); const [slot, setSlot] = useState('');
    const [slots, setSlots] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [sending, setSending] = useState(false); const [retry, setRetry] = useState(0);
    const [contact, setContact] = useState<BookingContact>({ firstName: '', lastName: '', email: '', phone: '' });
    const [slotNotice, setSlotNotice] = useState('');
    const [error, setError] = useState(''); const [success, setSuccess] = useState<Confirmation | null>(null);
    const [bounds, setBounds] = useState({ min: '', max: '', month: '' });
    const requestId = useRef(''); const service = config.services.find(item => item.id === selected); const heading = useRef<HTMLHeadingElement>(null);
    useEffect(() => { const now = new Date(); const min = localParts(new Date(+now + config.leadHours * 3600000), config.timeZone).date; setBounds({ min, max: localParts(new Date(+now + config.horizonDays * 86400000), config.timeZone).date, month: min.slice(0, 7) }); }, [config.timeZone, config.horizonDays, config.leadHours]);
    useEffect(() => { heading.current?.focus(); }, [step, success]);
    useEffect(() => {
        setSlot(''); setSlots([]); setLoading(false); if (!selected || !date) return;
        const controller = new AbortController(); setLoading(true); setError('');
        const timeout = setTimeout(() => { controller.abort(); setLoading(false); setError(languageRef.current === 'bg' ? 'Зареждането се забави. Опитай отново.' : 'Loading timed out. Please retry.'); }, 15000);
        fetch(`/api/booking/slots?service=${encodeURIComponent(selected)}&date=${date}`, { signal: controller.signal, cache: 'no-store' }).then(async response => { if (!response.ok) throw new Error(languageRef.current === 'bg' ? 'Часовете не могат да бъдат заредени.' : 'Unable to load available times.'); return response.json(); }).then(data => setSlots(Array.isArray(data.slots) ? data.slots : [])).catch(error => { if (!controller.signal.aborted) setError(error.message); }).finally(() => { clearTimeout(timeout); if (!controller.signal.aborted) setLoading(false); });
        return () => { clearTimeout(timeout); controller.abort(); };
    }, [selected, date, retry]);
    const locale = bg ? 'bg-BG' : 'en-GB';
    const time = (value: string) => new Intl.DateTimeFormat(locale, { hour: '2-digit', minute: '2-digit', hourCycle: 'h23', timeZone: config.timeZone, timeZoneName: 'short' }).format(new Date(value));
    const fullDate = (value: string) => new Intl.DateTimeFormat(locale, { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', timeZone: config.timeZone }).format(new Date(value));
    const labels = bg ? ['Услуга', 'Дата и час', 'Твоите данни', 'Потвърждение'] : ['Service', 'Date & time', 'Your details', 'Review'];
    const move = (next: number) => { setError(''); setStep(next); };
    const button = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-foreground px-5 text-sm font-semibold text-background disabled:cursor-not-allowed disabled:opacity-35';
    const input = 'mt-2 min-h-12 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-foreground';
    async function submit() {
        if (sending || !service || !slot) return; const normalized = normalizeBookingContact(contact);
        if (!normalized) { setError(bg ? 'Провери имената, имейла и телефона.' : 'Check your names, email and phone.'); setStep(2); return; }
        setSending(true); setError(''); if (!requestId.current) requestId.current = crypto.randomUUID();
        try { const response = await fetch('/api/booking/reservations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...normalized, serviceId: selected, startTime: slot, requestId: requestId.current }) }); const data = await response.json(); if (!response.ok) { if (response.status === 409) { requestId.current = ''; if (/time is no longer|overlaps/i.test(data.error || '')) { setSlotNotice(bg ? 'Избраният час вече е зает. Избери друг от обновения списък.' : 'Your selected time was just taken. Choose from the refreshed list.'); setRetry(value => value + 1); setStep(1); } } throw new Error(data.error || (bg ? 'Записването не успя. Опитай отново.' : 'Booking failed. Please retry.')); } setSuccess(data); }
        catch (error) { setError(error instanceof Error ? error.message : 'Please retry'); } finally { setSending(false); }
    }
    return <main className="min-h-screen bg-background px-4 pb-20 pt-28 text-foreground sm:px-8"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.24em] text-muted-foreground">NecrotixLab / Appointments</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{config.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{config.description}</p></div><div className="flex rounded-lg border border-border p-1" aria-label="Language">{(['bg', 'en'] as const).map(lang => <button type="button" key={lang} onClick={() => setLanguage(lang)} aria-pressed={language === lang} className={`min-h-9 rounded-md px-3 text-xs ${language === lang ? 'bg-muted font-bold' : 'text-muted-foreground'}`}>{lang === 'bg' ? 'Български' : 'English'}</button>)}</div></header>
        <div className="overflow-hidden rounded-2xl border border-border bg-background shadow-sm lg:grid lg:grid-cols-[290px_minmax(0,1fr)]"><aside className="border-b border-border bg-muted/30 p-6 lg:border-b-0 lg:border-r"><div className="lg:sticky lg:top-8"><div className="flex size-12 items-center justify-center rounded-2xl border border-border bg-background text-lg font-black">N<span className="text-muted-foreground">.</span></div><p className="mt-5 text-xs text-muted-foreground">{bg ? 'Среща с' : 'Meet with'}</p><h2 className="mt-1 text-lg font-bold">Dr. Necrotix</h2><p className="mt-4 text-xl font-semibold">{service?.title || (bg ? 'Избери своята консултация' : 'Choose your consultation')}</p>{service?.category && <p className="mt-2 text-xs text-muted-foreground">{service.category}</p>}<div className="mt-5 space-y-3 text-sm text-muted-foreground">{service && <><p className="flex items-center gap-2"><Clock className="size-4 shrink-0" />{service.duration} {bg ? 'минути' : 'minutes'}</p><p className="flex items-center gap-2"><Video className="size-4 shrink-0" />{service.platform === 'CALDIY' || service.platform === 'OTHER' ? (bg ? 'Уточнява се с организатора' : 'Arranged with the organizer') : service.platform.replace(/_/g, ' ')}</p></>}<p className="flex items-center gap-2"><Globe2 className="size-4 shrink-0" />{config.timeZone}</p>{slot && <p className="flex items-start gap-2 text-foreground"><CalendarDays className="mt-0.5 size-4 shrink-0" /><span className="capitalize">{fullDate(slot)}<span className="mt-1 block text-xs">{time(slot)}</span></span></p>}</div>{!success && <p className="mt-6 border-t border-border pt-5 text-xs leading-6 text-muted-foreground">{config.approvalRequired ? (bg ? 'Заявката се одобрява от организатора. Ще получиш актуализация по имейл.' : 'The organizer reviews your request. You will receive an email update.') : (bg ? 'Избраният час се потвърждава след изпращане.' : 'Your time is confirmed after submission.')}</p>}<Link href="/contact" className="mt-5 inline-block text-xs font-medium underline underline-offset-4">{bg ? 'Имаш въпрос?' : 'Need help?'}</Link></div></aside>
            <section className="min-w-0 p-5 sm:p-8">{success ? <div role="status" className="mx-auto max-w-lg py-6"><span className="flex size-14 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-600"><CheckCircle2 className="size-7" /></span><h2 ref={heading} tabIndex={-1} className="mt-6 text-2xl font-bold outline-none">{success.status === 'PENDING' ? (bg ? 'Заявката е получена' : 'Request received') : (bg ? 'Срещата е потвърдена' : 'Appointment confirmed')}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{success.status === 'PENDING' ? (bg ? 'Часът е заявен и очаква одобрение. Все още не е потвърдена среща.' : 'Your time is requested and awaits organizer approval. It is not a confirmed appointment yet.') : (bg ? 'Часът ти е запазен. Очакваме те на срещата.' : 'Your time is reserved. We look forward to meeting you.')}</p><div className="mt-6 space-y-3 rounded-xl border border-border p-5"><p className="font-semibold">{success.title}</p><p className="text-sm capitalize">{fullDate(success.startTime)}</p><p className="text-sm">{time(success.startTime)} - {time(success.endTime)}</p><p className="flex items-center gap-2 break-all text-sm"><Mail className="size-4 shrink-0" />{contact.email}</p></div><p className="mt-5 text-xs leading-6 text-muted-foreground">{bg ? 'Информацията за срещата се изпраща по имейл. Ако не я получиш, провери Spam или се свържи с нас. За промяна или отказ използвай страницата за контакт.' : 'Meeting details are sent by email. Check your spam folder or contact us if they do not arrive. Use the contact page to request a change or cancellation.'}</p><Link href="/contact" className={`${button} mt-6`}>{bg ? 'Контакт с организатора' : 'Contact the organizer'}</Link></div> : <><ol aria-label={bg ? 'Стъпки за записване' : 'Booking steps'} className="mb-8 grid grid-cols-4 gap-2 border-b border-border pb-6">{labels.map((label, index) => <li key={label}><button type="button" disabled={index > step || sending} onClick={() => move(index)} aria-current={step === index ? 'step' : undefined} className={`flex w-full flex-col items-start gap-2 text-left text-[10px] sm:flex-row sm:items-center sm:text-xs ${index === step ? 'font-semibold text-foreground' : 'text-muted-foreground'}`}><span className={`flex size-7 shrink-0 items-center justify-center rounded-full border ${index <= step ? 'border-foreground bg-foreground text-background' : 'border-border'}`}>{index < step ? <Check className="size-3.5" /> : index + 1}</span>{label}</button></li>)}</ol><h2 ref={heading} tabIndex={-1} className="mb-2 text-xl font-bold outline-none">{labels[step]}</h2>
                {step === 0 && <><p className="mb-6 text-sm text-muted-foreground">{bg ? 'Избери услугата, за която искаш да поговорим.' : 'Choose what you would like to discuss.'}</p><div className="grid gap-3 sm:grid-cols-2">{config.services.map(item => <button key={item.id} type="button" onClick={() => { if (selected !== item.id) { setSelected(item.id); setSlot(''); setSlotNotice(''); requestId.current = ''; } move(1); }} className="group rounded-xl border border-border p-5 text-left transition hover:border-foreground/50 hover:bg-muted/30"><span className="flex items-start justify-between gap-3"><CalendarDays className="size-5 text-muted-foreground" /><ArrowRight className="size-4 text-muted-foreground transition group-hover:translate-x-1" /></span><h3 className="mt-4 font-semibold">{item.title}</h3>{item.category && <p className="mt-2 text-[10px] uppercase tracking-wider text-muted-foreground">{item.category}</p>}<p className="mt-2 text-xs leading-6 text-muted-foreground">{item.description}</p><p className="mt-4 text-xs font-medium">{item.duration} {bg ? 'минути' : 'minutes'}</p></button>)}</div></>}
                {step === 1 && <>{slotNotice && <p role="status" className="mb-4 rounded-xl border border-amber-500/30 p-4 text-sm">{slotNotice}</p>}<p className="mb-6 text-sm text-muted-foreground">{bg ? 'Избери дата, след това свободен час.' : 'Choose a date, then an available time.'}</p><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_190px]"><div>{bounds.month && <BookingDatePicker month={bounds.month} onMonth={month => setBounds(value => ({ ...value, month }))} date={date} onDate={value => { setDate(value); setSlotNotice(''); requestId.current = ''; }} min={bounds.min} max={bounds.max} weekdays={config.weekdays} blockedDates={config.blockedDates} language={language} />}</div><div className="border-t border-border pt-5 xl:border-l xl:border-t-0 xl:pl-5 xl:pt-0"><h3 className="mb-3 text-sm font-semibold">{bg ? 'Свободни часове' : 'Available times'}</h3>{!date && <p className="text-xs leading-6 text-muted-foreground">{bg ? 'Избери дата от календара.' : 'Select a date from the calendar.'}</p>}{loading && <p role="status" className="text-xs text-muted-foreground">{bg ? 'Проверка на часовете...' : 'Checking availability...'}</p>}{date && !loading && !slots.length && !error && <p className="rounded-xl bg-muted/50 p-4 text-xs leading-6 text-muted-foreground">{bg ? 'Няма свободни часове. Избери друга дата.' : 'No times available. Please choose another date.'}</p>}<div className="grid max-h-80 grid-cols-2 gap-2 overflow-y-auto xl:grid-cols-1">{slots.map(value => <button key={value} type="button" aria-pressed={slot === value} onClick={() => { setSlot(value); setSlotNotice(''); requestId.current = ''; }} className={`min-h-11 rounded-lg border px-2 text-xs font-medium ${slot === value ? 'border-foreground bg-foreground text-background' : 'border-border hover:border-foreground/50'}`}>{time(value)}</button>)}</div></div></div><div className="mt-7 flex items-center justify-between gap-3"><button type="button" onClick={() => move(0)} className="inline-flex min-h-11 items-center gap-2 text-sm"><ArrowLeft className="size-4" />{bg ? 'Назад' : 'Back'}</button><button type="button" disabled={!slot || loading} onClick={() => move(2)} className={button}>{bg ? 'Продължи' : 'Continue'}<ArrowRight className="size-4" /></button></div></>}
                {step === 2 && <form className="mt-6 space-y-5" onSubmit={event => { event.preventDefault(); const normalized = normalizeBookingContact(contact); if (!normalized) { setError(bg ? 'Попълни две имена, валиден имейл и телефон с код на държавата.' : 'Enter both names, a valid email and a phone with country code.'); return; } setContact(normalized); move(3); }}><div className="grid gap-4 sm:grid-cols-2">{[['firstName', bg ? 'Име' : 'First name', 'given-name'], ['lastName', bg ? 'Фамилия' : 'Last name', 'family-name'], ['email', bg ? 'Имейл' : 'Email', 'email'], ['phone', bg ? 'Телефон с код на държавата' : 'Phone with country code', 'tel']].map(([name, label, autoComplete]) => <label key={name} className="text-sm">{label}<input required name={name} type={name === 'email' ? 'email' : name === 'phone' ? 'tel' : 'text'} autoComplete={autoComplete} maxLength={name === 'email' ? 254 : name === 'phone' ? 30 : 80} placeholder={name === 'phone' ? '+359...' : undefined} value={contact[name as keyof BookingContact]} onChange={event => { setContact(value => ({ ...value, [name]: event.target.value })); requestId.current = ''; }} className={input} /></label>)}</div><p className="text-xs leading-6 text-muted-foreground">{bg ? 'Използваме данните за организиране на срещата. Историята се пази 30 дни след срещата или отказа.' : 'We use these details to arrange the meeting. History is kept for 30 days after the meeting or decline.'} <Link href="/privacy" className="underline">{bg ? 'Поверителност' : 'Privacy'}</Link></p><div className="flex items-center justify-between gap-3"><button type="button" onClick={() => move(1)} className="inline-flex min-h-11 items-center gap-2 text-sm"><ArrowLeft className="size-4" />{bg ? 'Назад' : 'Back'}</button><button className={button}>{bg ? 'Преглед на заявката' : 'Review appointment'}<ArrowRight className="size-4" /></button></div></form>}
                {step === 3 && <div className="mt-6"><p className="text-sm text-muted-foreground">{bg ? 'Провери избрания час и данните си преди изпращане.' : 'Check your appointment and details before submitting.'}</p><dl className="mt-5 divide-y divide-border rounded-xl border border-border px-5">{[[bg ? 'Услуга' : 'Service', service?.title], [bg ? 'Дата и час' : 'Date & time', slot ? `${fullDate(slot)}, ${time(slot)}` : ''], [bg ? 'Имена' : 'Name', `${contact.firstName} ${contact.lastName}`], [bg ? 'Имейл' : 'Email', contact.email], [bg ? 'Телефон' : 'Phone', contact.phone]].map(([label, value]) => <div key={label} className="grid gap-1 py-4 text-sm sm:grid-cols-[120px_1fr]"><dt className="text-muted-foreground">{label}</dt><dd className="break-words font-medium">{value}</dd></div>)}</dl><p className="mt-5 text-xs leading-6 text-muted-foreground">{config.approvalRequired ? (bg ? 'Изпращаш заявка за одобрение. Календарната покана се изпраща след потвърждение от организатора.' : 'You are submitting a request for approval. Calendar invitations follow organizer confirmation.') : (bg ? 'С изпращането запазваш избрания час.' : 'Submitting reserves your selected time.')}</p><div className="mt-6 flex items-center justify-between gap-3"><button type="button" disabled={sending} onClick={() => move(2)} className="inline-flex min-h-11 items-center gap-2 text-sm"><ArrowLeft className="size-4" />{bg ? 'Редактирай' : 'Edit details'}</button><button type="button" disabled={sending} onClick={() => void submit()} className={button}>{sending ? (bg ? 'Изпращане...' : 'Sending...') : (bg ? 'Запази час' : 'Book appointment')}<Check className="size-4" /></button></div></div>}
                {error && <div role="alert" className="mt-5 rounded-xl border border-rose-500/30 bg-rose-500/5 p-4 text-sm"><p>{error}</p>{step === 1 && <button type="button" onClick={() => setRetry(value => value + 1)} className="mt-3 min-h-9 text-xs font-semibold underline">{bg ? 'Опитай отново' : 'Retry availability'}</button>}</div>}
            </> }</section></div>
    </div></main>;
}
