'use client';
import { useState, type FormEvent } from 'react';

type Result = { kind: string; code?: string; url?: string; note: string; channel?: string; expires?: string; server?: { id: string; name: string; description?: string; icon?: string; verificationLevel?: number | null; features?: string[]; members?: number | null; online?: number | null; created?: string | null; invite?: string; channels?: number }; user?: { id: string; username: string; displayName: string; avatar: string; bot: boolean; created: string | null } };
export function DiscordLookup() {
    const [kind, setKind] = useState<'invite' | 'server' | 'user'>('invite');
    const [query, setQuery] = useState(''), [result, setResult] = useState<Result | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
    async function lookup(event: FormEvent) {
        event.preventDefault(); setBusy(true); setResult(null); setError('');
        try { const response = await fetch(`/api/tools/discord-lookup?kind=${kind}&q=${encodeURIComponent(query)}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Lookup failed.'); setResult(data); }
        catch (reason) { setError(reason instanceof Error ? reason.message : 'Lookup failed.'); }
        finally { setBusy(false); }
    }
    return <div className="space-y-5">
        <div className="flex flex-wrap gap-2" role="group" aria-label="Discord lookup type">{([['invite', 'Invite link', 'discord.gg/code'], ['server', 'Server ID', 'Server ID with public widget'], ['user', 'User ID', 'Requires a configured bot']] as const).map(([value, label, title]) => <button key={value} type="button" title={title} onClick={() => { setKind(value); setQuery(''); setResult(null); setError(''); }} className={`rounded-lg border px-4 py-2 text-sm ${kind === value ? 'border-cyan-500 text-cyan-500' : 'border-border'}`}>{label}</button>)}</div>
        <form onSubmit={lookup} className="flex flex-col gap-2 sm:flex-row"><input required maxLength={160} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={kind === 'invite' ? 'https://discord.gg/example or invite code' : 'Discord ID (17-20 digits)'} aria-label="Discord invite or ID" className="min-h-11 min-w-0 flex-1 rounded-xl border border-border bg-background px-4 text-sm" /><button disabled={busy} className="rounded-xl bg-foreground px-5 py-3 text-sm font-bold text-background disabled:opacity-50">{busy ? 'Checking...' : 'Lookup'}</button></form>
        <p className="text-xs leading-5 text-muted-foreground">Invite links show public server details and approximate counts. A server ID works only if its widget is enabled. User profiles require a bot token set by the site owner; Discord does not offer anonymous profile search by name.</p>
        {error && <p role="alert" className="rounded-xl border border-rose-500/40 p-4 text-sm text-rose-500">{error}</p>}
        {result && <div className="space-y-4"><section className="rounded-xl border border-border p-5"><p className="text-xs uppercase tracking-wider text-cyan-500">{result.kind}</p><h2 className="mt-2 break-words text-xl font-bold">{result.server?.name || result.user?.displayName || result.user?.username || result.code}</h2><p className="mt-2 text-xs text-muted-foreground">{result.note}</p></section><div className="grid gap-4 sm:grid-cols-2"><Panel title="Identity"><Row label="Server ID" value={result.server?.id} /><Row label="User ID" value={result.user?.id} /><Row label="Username" value={result.user?.username} /><Row label="Bot" value={result.user ? result.user.bot ? 'Yes' : 'No' : undefined} /><Row label="Description" value={result.server?.description} /><Row label="Created" value={result.server?.created || result.user?.created} /><Row label="Verification level" value={result.server?.verificationLevel == null ? undefined : String(result.server.verificationLevel)} /></Panel><Panel title="Public activity"><Row label="Members (approximate)" value={result.server?.members == null ? undefined : result.server.members.toLocaleString()} /><Row label="Online (approximate)" value={result.server?.online == null ? undefined : result.server.online.toLocaleString()} /><Row label="Public widget channels" value={result.server?.channels == null ? undefined : String(result.server.channels)} /><Row label="Invite channel" value={result.channel} /><Row label="Invite expiry" value={result.expires} /><Row label="Features" value={result.server?.features?.join(', ')} /></Panel></div>{result.url && <a className="inline-block rounded-lg border border-border px-4 py-2 text-sm text-cyan-500" href={result.url} target="_blank" rel="noopener noreferrer">Open public invite</a>}</div>}
    </div>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-border p-5"><h3 className="mb-4 font-bold">{title}</h3><dl className="space-y-3 text-sm">{children}</dl></section>; }
function Row({ label, value }: { label: string; value?: string | null }) { return value ? <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="break-words">{value}</dd></div> : null; }
