import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { prisma } from '@/lib/prisma';
import { calOrigin } from '@addons/Booking/settings';
export const dynamic = 'force-dynamic';
const statuses = ['PENDING', 'CONFIRMED', 'CANCELLED', 'REJECTED', 'RESCHEDULED', 'COMPLETED'];
export default async function BookingsPage({ searchParams }: { searchParams: Promise<{ status?: string; page?: string; view?: string; q?: string }> }) {
    const session = await auth(); if (!session?.user || !['OWNER', 'ADMIN'].includes(session.user.role)) redirect('/admin');
    const params = await searchParams; const status = statuses.includes(params.status || '') ? params.status : undefined;
    const page = Math.min(10000, Math.max(1, Number.parseInt(params.page || '1', 10) || 1));
    const view = ['upcoming', 'past', 'unconfirmed'].includes(params.view || '') ? params.view : 'upcoming';
    const q = (params.q || '').trim().slice(0, 120);
    const now = new Date();
    const where = { ...(status ? { status } : {}), ...(view === 'upcoming' ? { startTime: { gte: now } } : view === 'past' ? { startTime: { lt: now } } : { status: 'PENDING' }), ...(q ? { OR: [{ customerName: { contains: q, mode: 'insensitive' as const } }, { email: { contains: q, mode: 'insensitive' as const } }, { title: { contains: q, mode: 'insensitive' as const } }] } : {}) };
    const href = (nextPage: number, nextStatus = status || '', nextView = view) => `/admin/bookings?view=${nextView}&page=${nextPage}&status=${nextStatus}&q=${encodeURIComponent(q)}`;
    const [items, total, pending] = await Promise.all([prisma.bookingReservation.findMany({ where, orderBy: { startTime: view === 'past' ? 'desc' : 'asc' }, include: { project: { select: { status: true } } }, take: 30, skip: (page - 1) * 30 }), prisma.bookingReservation.count({ where }), prisma.bookingReservation.count({ where: { status: 'PENDING' } })]);
    const origin = calOrigin(process.env.CALDIY_ORIGIN);
    const time = (value: Date) => new Intl.DateTimeFormat('bg-BG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Europe/Sofia' }).format(value);
    return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs text-muted-foreground">Booking addon</p><h1 className="mt-2 text-3xl font-black">Reservations</h1><p className="mt-3 text-sm text-muted-foreground">{total} matching reservations · {pending} awaiting approval · times in Europe/Sofia</p></div><div className="flex flex-wrap gap-4 text-sm"><Link href="/admin/bookings/projects" className="underline">Projects</Link><Link href="/admin/bookings/customers" className="underline">Customers</Link><Link href="/admin/addons/booking" className="underline">Settings</Link>{origin && <a href={`${origin}/bookings`} target="_blank" rel="noopener noreferrer" className="underline">Manage in Cal.diy</a>}</div></header>
        {!process.env.CALDIY_WEBHOOK_SECRET && <p role="status" className="rounded-xl border border-amber-500/30 p-4 text-sm">Configure CALDIY_WEBHOOK_SECRET and the Cal.diy webhook to record new reservations here.</p>}
        <nav aria-label="Booking views" className="flex flex-wrap gap-2 border-b border-border">{['upcoming', 'past', 'unconfirmed'].map(tab => <Link key={tab} href={href(1, '', tab)} aria-current={view === tab ? 'page' : undefined} className={`min-h-11 border-b-2 px-4 py-3 text-sm capitalize ${view === tab ? 'border-foreground font-semibold' : 'border-transparent text-muted-foreground'}`}>{tab}</Link>)}</nav>
        <form className="flex flex-wrap gap-3"><input type="hidden" name="view" value={view} /><input type="hidden" name="status" value={status || ''} /><input name="q" defaultValue={q} maxLength={120} aria-label="Search reservations" placeholder="Search name, email or service" className="min-h-11 flex-1 rounded-lg border border-border bg-background px-3 text-sm" /><button className="min-h-11 rounded-lg border border-border px-4 text-sm">Search</button></form>
        <nav aria-label="Reservation status" className="flex flex-wrap gap-2"><Link href={href(1, '')} className="min-h-10 rounded-lg border border-border px-3 py-2 text-xs">All</Link>{statuses.map(item => <Link key={item} href={href(1, item)} aria-current={status === item ? 'page' : undefined} className={`min-h-10 rounded-lg border px-3 py-2 text-xs ${status === item ? 'border-foreground bg-muted' : 'border-border'}`}>{item.toLowerCase()}</Link>)}</nav>
        <div className="divide-y divide-border overflow-hidden rounded-xl border border-border">{items.map(item => <article key={item.id} className="grid gap-4 p-5 transition-colors hover:bg-muted/30 md:grid-cols-[1fr_1fr]"><div><p className="text-xs font-semibold text-muted-foreground">{item.status}</p><h2 className="mt-2 text-lg font-bold"><Link href={`/admin/bookings/${item.id}`} className="hover:underline">{item.title}</Link></h2>{item.project && <p className="mt-2 text-xs text-muted-foreground">Project: {item.project.status}</p>}<p className="mt-3 text-sm">{time(item.startTime)} - {time(item.endTime)}</p></div><div><h3 className="font-semibold">{item.customerName || 'No attendee name'}</h3><p className="mt-2 break-all text-sm">{item.email}</p><p className="mt-2 text-xs text-muted-foreground">Customer timezone: {item.timeZone || 'Not provided'}</p><Link href={`/admin/bookings/${item.id}`} className="mt-3 inline-block min-h-8 text-xs underline">Details & history</Link></div></article>)}{items.length === 0 && <p className="rounded-xl border border-dashed border-border p-8 text-sm text-muted-foreground">No recorded reservations. Existing Cal.diy bookings are not imported automatically; records arrive through signed webhook events.</p>}</div>
        <div className="flex justify-between text-sm">{page > 1 && <Link href={href(page - 1)} className="underline">Previous</Link>}{page * 30 < total && <Link href={href(page + 1)} className="ml-auto underline">Next</Link>}</div>
        <p className="text-xs text-muted-foreground">This is a synchronized record. Approve, cancel or reschedule in Cal.diy; webhook delivery updates this list.</p>
    </div>;
}
