import { AppointmentsCalendar } from '@/components/admin/AppointmentsCalendar';
import { bookingMonthRange } from '@addons/Booking/calendar-view';
import { localParts } from '@addons/Booking/availability';
import { sendBookingCalendarInvitations } from './actions';
import { BookingStatusBadge } from '@/components/admin/BookingStatusBadge';
import { bookingStatusFilter, bookingStatusLabel } from '@addons/Booking/status.mjs';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { prisma } from '@/lib/prisma';
export const dynamic = 'force-dynamic';
const statuses = ['PENDING', 'CONFIRMED', 'RESCHEDULED', 'DECLINED', 'COMPLETED'];
export default async function BookingsPage({ searchParams }: { searchParams: Promise<{ status?: string; page?: string; view?: string; q?: string; queued?: string; error?: string; month?: string }> }) {
    const session = await auth(); if (!session?.user || !['OWNER', 'ADMIN'].includes(session.user.role)) redirect('/admin');
    const params = await searchParams; const status = [...statuses, 'CANCELLED', 'REJECTED', 'ACTIVE'].includes(params.status || '') ? params.status : undefined;
    const page = Math.min(10000, Math.max(1, Number.parseInt(params.page || '1', 10) || 1));
    const view = ['upcoming', 'past', 'unconfirmed', 'calendar'].includes(params.view || '') ? params.view : 'upcoming';
    const q = (params.q || '').trim().slice(0, 120);
    const now = new Date(); const today = localParts(now, 'Europe/Sofia').date;
    const month = /^(20\d{2})-(0[1-9]|1[0-2])$/.test(params.month || '') ? params.month! : today.slice(0, 7);
    const range = view === 'calendar' ? bookingMonthRange(month) : null;
    const where = { AND: [bookingStatusFilter(view === 'unconfirmed' ? 'PENDING' : status), ...(range ? [{ startTime: range }] : []), ...(view === 'upcoming' ? [{ startTime: { gte: now } }] : view === 'past' ? [{ startTime: { lt: now } }] : []), ...(q ? [{ OR: [{ customerName: { contains: q, mode: 'insensitive' as const } }, { email: { contains: q, mode: 'insensitive' as const } }, { title: { contains: q, mode: 'insensitive' as const } }] }] : [])] };
    const href = (nextPage: number, nextStatus = status || '', nextView = view) => `/admin/bookings?month=${month}&view=${nextView}&page=${nextPage}&status=${nextStatus}&q=${encodeURIComponent(q)}`;
    const [items, total, pending] = await Promise.all([prisma.bookingReservation.findMany({ where, orderBy: { startTime: view === 'past' ? 'desc' : 'asc' }, include: { project: { select: { status: true } } }, take: view === 'calendar' ? 301 : 30, skip: view === 'calendar' ? 0 : (page - 1) * 30 }), prisma.bookingReservation.count({ where }), prisma.bookingReservation.count({ where: { status: 'PENDING' } })]);
    const time = (value: Date) => new Intl.DateTimeFormat('bg-BG', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Europe/Sofia' }).format(value);
    return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs text-muted-foreground">Booking addon</p><h1 className="mt-2 text-3xl font-black">Appointments</h1><p className="mt-3 text-sm text-muted-foreground">{total} matching appointments · {pending} awaiting approval · times in Europe/Sofia</p><p className="mt-2 text-xs text-muted-foreground">Историята се пази 30 дни след края на срещата или отказа/пренасочването. / History is kept for 30 days after the meeting ends or cancellation/supersession.</p></div><div className="flex flex-wrap gap-4 text-sm"><a href="/api/admin/bookings/export?scope=all" className="underline">Export all data (.csv)</a><a href={`/api/admin/bookings/export?scope=filtered&month=${month}&view=${view}&status=${status || ''}&q=${encodeURIComponent(q)}`} className="underline">Export filtered data (.csv)</a><Link href="/admin/bookings/projects" className="underline">Projects</Link><Link href="/admin/bookings/customers" className="underline">Customers</Link><Link href="/admin/addons/booking" className="underline">Settings</Link></div></header>
        {params.queued && <p role="status" className="rounded-xl border border-border p-4 text-sm">Invitations queued. Already delivered invitations are not sent again for the same booking version. Check delivery in reservation details.</p>}
        {params.error && <p role="alert" className="rounded-xl border border-amber-500/30 p-4 text-sm">{params.error}</p>}

        <nav aria-label="Booking views" className="flex flex-wrap gap-2 border-b border-border">{['upcoming', 'past', 'unconfirmed', 'calendar'].map(tab => <Link key={tab} href={href(1, '', tab)} aria-current={view === tab ? 'page' : undefined} className={`min-h-11 border-b-2 px-4 py-3 text-sm capitalize ${view === tab ? 'border-foreground font-semibold' : 'border-transparent text-muted-foreground'}`}>{tab}</Link>)}</nav>
        <form className="flex flex-wrap gap-3"><input type="hidden" name="view" value={view} /><input type="hidden" name="month" value={month} /><input type="hidden" name="status" value={status || ''} /><input name="q" defaultValue={q} maxLength={120} aria-label="Search appointments" placeholder="Search name, email or service" className="min-h-11 flex-1 rounded-lg border border-border bg-background px-3 text-sm" /><button className="min-h-11 rounded-lg border border-border px-4 text-sm">Search</button></form>
        <nav aria-label="Appointment status" className="flex flex-wrap gap-2"><Link href={href(1, '')} className="min-h-10 rounded-lg border border-border px-3 py-2 text-xs">All</Link>{statuses.map(item => <Link key={item} href={href(1, item)} aria-current={status === item ? 'page' : undefined} className={`min-h-10 rounded-lg border px-3 py-2 text-xs ${status === item ? 'border-foreground bg-muted' : 'border-border'}`}>{bookingStatusLabel({ status: item })}</Link>)}</nav>
        {view === 'calendar' && <AppointmentsCalendar key={month} filters={new URLSearchParams({ status: status || '', q }).toString()} month={month} today={today} more={items.length > 300} appointments={items.slice(0, 300).map(item => ({ id: item.id, title: item.title, customerName: item.customerName, status: item.status, startTime: item.startTime.toISOString(), endTime: item.endTime.toISOString(), rescheduledAt: item.rescheduledAt?.toISOString() || null, rescheduledFromUid: item.rescheduledFromUid }))} />}
        {view !== 'calendar' && <>
        <form action={sendBookingCalendarInvitations} className="space-y-4"><div className="flex flex-wrap gap-3"><button name="scope" value="selected" className="min-h-11 rounded-lg border border-border px-4 text-xs font-semibold">Send calendar invitations for selected</button><button name="scope" value="all" className="min-h-11 rounded-lg border border-border px-4 text-xs">Send for all upcoming confirmed bookings (max 200)</button><a href="/api/admin/bookings/calendar?scope=all" className="min-h-11 rounded-lg border border-border px-4 py-3 text-xs">Download all upcoming as .ics</a><button formAction="/api/admin/bookings/export" name="scope" value="selected" className="min-h-11 rounded-lg border border-border px-4 text-xs">Export selected data (.csv)</button><button formAction="/api/admin/bookings/calendar" name="scope" value="selected" className="min-h-11 rounded-lg border border-border px-4 text-xs">Download selected as .ics</button></div><p className="text-xs text-muted-foreground">Selections below apply to confirmed upcoming appointments. Recipient settings control which side receives invitations. .ics downloads import events into the calendar you choose.</p>
        <div className="divide-y divide-border overflow-hidden rounded-xl border border-border">{items.map(item => <article key={item.id} className="grid gap-4 p-5 transition-colors hover:bg-muted/30 md:grid-cols-[1fr_1fr]"><div><label className="mb-3 flex min-h-8 items-center gap-2 text-xs"><input type="checkbox" name="ids" value={item.id} />Select booking</label><BookingStatusBadge booking={item} /><h2 className="mt-2 text-lg font-bold"><Link href={`/admin/bookings/${item.id}`} className="hover:underline">{item.title}</Link></h2>{item.project && <p className="mt-2 text-xs text-muted-foreground">Project: {item.project.status}</p>}<p className="mt-3 text-sm">{time(item.startTime)} - {time(item.endTime)}</p></div><div><h3 className="font-semibold">{item.customerName || 'No attendee name'}</h3><p className="mt-2 break-all text-sm">{item.email}</p><p className="mt-2 text-xs text-muted-foreground">Customer timezone: {item.timeZone || 'Not provided'}</p><Link href={`/admin/bookings/${item.id}`} className="mt-3 inline-block min-h-8 text-xs underline">Details & history</Link></div></article>)}{items.length === 0 && <p className="rounded-xl border border-dashed border-border p-8 text-sm text-muted-foreground">No appointments yet. New requests appear here when clients book through the booking page.</p>}</div>
        </form>
        <div className="flex justify-between text-sm">{page > 1 && <Link href={href(page - 1)} className="underline">Previous</Link>}{page * 30 < total && <Link href={href(page + 1)} className="ml-auto underline">Next</Link>}</div>
        <p className="text-xs text-muted-foreground">Open an appointment to approve, decline, reschedule or update its joining details.</p>
        </>}
    </div>;
}
